/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        Breadcrumb: (typeof import('./../components/Layout/Breadcrumb.vue'))['default'];
        Description: (typeof import('./../components/Description/index.vue'))['default'];
        ElAside: (typeof import('element-plus/es'))['ElAside'];
        ElAutoResizer: (typeof import('element-plus/es'))['ElAutoResizer'];
        ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb'];
        ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem'];
        ElButton: (typeof import('element-plus/es'))['ElButton'];
        ElCard: (typeof import('element-plus/es'))['ElCard'];
        ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox'];
        ElCheckboxGroup: (typeof import('element-plus/es'))['ElCheckboxGroup'];
        ElCol: (typeof import('element-plus/es'))['ElCol'];
        ElCollapseTransition: (typeof import('element-plus/es'))['ElCollapseTransition'];
        ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider'];
        ElContainer: (typeof import('element-plus/es'))['ElContainer'];
        ElDescriptions: (typeof import('element-plus/es'))['ElDescriptions'];
        ElDescriptionsItem: (typeof import('element-plus/es'))['ElDescriptionsItem'];
        ElDialog: (typeof import('element-plus/es'))['ElDialog'];
        ElDivider: (typeof import('element-plus/es'))['ElDivider'];
        ElDropdown: (typeof import('element-plus/es'))['ElDropdown'];
        ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem'];
        ElEmpty: (typeof import('element-plus/es'))['ElEmpty'];
        ElForm: (typeof import('element-plus/es'))['ElForm'];
        ElFormItem: (typeof import('element-plus/es'))['ElFormItem'];
        ElHeader: (typeof import('element-plus/es'))['ElHeader'];
        ElIcon: (typeof import('element-plus/es'))['ElIcon'];
        ElInput: (typeof import('element-plus/es'))['ElInput'];
        ElMain: (typeof import('element-plus/es'))['ElMain'];
        ElMenu: (typeof import('element-plus/es'))['ElMenu'];
        ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem'];
        ElOption: (typeof import('element-plus/es'))['ElOption'];
        ElPagination: (typeof import('element-plus/es'))['ElPagination'];
        ElPopover: (typeof import('element-plus/es'))['ElPopover'];
        ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup'];
        ElRow: (typeof import('element-plus/es'))['ElRow'];
        ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar'];
        ElSelect: (typeof import('element-plus/es'))['ElSelect'];
        ElTable: (typeof import('element-plus/es'))['ElTable'];
        ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn'];
        ElTableV2: (typeof import('element-plus/es'))['ElTableV2'];
        ElTag: (typeof import('element-plus/es'))['ElTag'];
        ElTooltip: (typeof import('element-plus/es'))['ElTooltip'];
        ElWatermark: (typeof import('element-plus/es'))['ElWatermark'];
        FilePreview: (typeof import('./../components/FilePreview/index.vue'))['default'];
        HistoryTabs: (typeof import('./../components/Layout/HistoryTabs.vue'))['default'];
        ParentMenuView: (typeof import('./../components/Layout/ParentMenuView.vue'))['default'];
        ParentView: (typeof import('./../components/Layout/ParentView.vue'))['default'];
        RichTextEditor: (typeof import('./../components/RichTextEditor/index.vue'))['default'];
        RouterLink: (typeof import('vue-router'))['RouterLink'];
        RouterView: (typeof import('vue-router'))['RouterView'];
        SubMenu: (typeof import('./../components/Layout/SubMenu.vue'))['default'];
        Table: (typeof import('./../components/Table/index.vue'))['default'];
        TableSetting: (typeof import('./../components/Table/components/TableSetting.vue'))['default'];
        TableV2: (typeof import('./../components/TableV2/index.vue'))['default'];
        Upload: (typeof import('./../components/Upload/index.vue'))['default'];
        XCheckbox: (typeof import('./../components/Form/components/XCheckbox.vue'))['default'];
        XDialogForm: (typeof import('./../components/Form/XDialogForm.vue'))['default'];
        XEditTable: (typeof import('./../components/EditTable/XEditTable.vue'))['default'];
        XEditTableItem: (typeof import('./../components/EditTable/XEditTableItem.vue'))['default'];
        XForm: (typeof import('./../components/Form/XForm.vue'))['default'];
        XFormItem: (typeof import('./../components/Form/XFormItem.vue'))['default'];
        XLayout: (typeof import('./../components/Layout/XLayout.vue'))['default'];
        XLogo: (typeof import('./../components/Layout/XLogo.vue'))['default'];
        XRadio: (typeof import('./../components/Form/components/XRadio.vue'))['default'];
        XSearchForm: (typeof import('./../components/Form/XSearchForm.vue'))['default'];
        XSelect: (typeof import('./../components/Form/components/XSelect.vue'))['default'];
        XUser: (typeof import('./../components/Layout/XUser.vue'))['default'];
    }
    export interface ComponentCustomProperties {
        vLoading: (typeof import('element-plus/es'))['ElLoadingDirective'];
    }
}
