/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        Description: (typeof import('./../components/description/index.vue'))['default'];
        ElAside: (typeof import('element-plus/es'))['ElAside'];
        ElAutoResizer: (typeof import('element-plus/es'))['ElAutoResizer'];
        ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb'];
        ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem'];
        ElButton: (typeof import('element-plus/es'))['ElButton'];
        ElCard: (typeof import('element-plus/es'))['ElCard'];
        ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox'];
        ElCheckboxGroup: (typeof import('element-plus/es'))['ElCheckboxGroup'];
        ElCol: (typeof import('element-plus/es'))['ElCol'];
        ElCollapseTransition: (typeof import('element-plus/es'))['ElCollapseTransition'];
        ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider'];
        ElContainer: (typeof import('element-plus/es'))['ElContainer'];
        ElDescriptions: (typeof import('element-plus/es'))['ElDescriptions'];
        ElDescriptionsItem: (typeof import('element-plus/es'))['ElDescriptionsItem'];
        ElDialog: (typeof import('element-plus/es'))['ElDialog'];
        ElDivider: (typeof import('element-plus/es'))['ElDivider'];
        ElDropdown: (typeof import('element-plus/es'))['ElDropdown'];
        ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem'];
        ElEmpty: (typeof import('element-plus/es'))['ElEmpty'];
        ElForm: (typeof import('element-plus/es'))['ElForm'];
        ElFormItem: (typeof import('element-plus/es'))['ElFormItem'];
        ElHeader: (typeof import('element-plus/es'))['ElHeader'];
        ElIcon: (typeof import('element-plus/es'))['ElIcon'];
        ElInput: (typeof import('element-plus/es'))['ElInput'];
        ElMain: (typeof import('element-plus/es'))['ElMain'];
        ElMenu: (typeof import('element-plus/es'))['ElMenu'];
        ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem'];
        ElOption: (typeof import('element-plus/es'))['ElOption'];
        ElPagination: (typeof import('element-plus/es'))['ElPagination'];
        ElPopover: (typeof import('element-plus/es'))['ElPopover'];
        ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup'];
        ElRow: (typeof import('element-plus/es'))['ElRow'];
        ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar'];
        ElSelect: (typeof import('element-plus/es'))['ElSelect'];
        ElTable: (typeof import('element-plus/es'))['ElTable'];
        ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn'];
        ElTableV2: (typeof import('element-plus/es'))['ElTableV2'];
        ElTag: (typeof import('element-plus/es'))['ElTag'];
        ElTooltip: (typeof import('element-plus/es'))['ElTooltip'];
        HistoryTabs: (typeof import('./../components/layout/history-tabs.vue'))['default'];
        ParentMenuView: (typeof import('./../components/layout/parent-menu-view.vue'))['default'];
        ParentView: (typeof import('./../components/layout/parent-view.vue'))['default'];
        RouterLink: (typeof import('vue-router'))['RouterLink'];
        RouterView: (typeof import('vue-router'))['RouterView'];
        SubMenu: (typeof import('./../components/layout/sub-menu.vue'))['default'];
        Table: (typeof import('./../components/table/index.vue'))['default'];
        TableSetting: (typeof import('./../components/table/components/table-setting.vue'))['default'];
        TableV2: (typeof import('./../components/table-v2/index.vue'))['default'];
        XBreadcrumb: (typeof import('./../components/layout/x-breadcrumb.vue'))['default'];
        XCheckbox: (typeof import('./../components/form/components/x-checkbox.vue'))['default'];
        XDescription: (typeof import('./../components/description/index.vue'))['default'];
        XDialogForm: (typeof import('./../components/form/x-dialog-form.vue'))['default'];
        XForm: (typeof import('./../components/form/x-form.vue'))['default'];
        XFormItem: (typeof import('./../components/form/x-form-item.vue'))['default'];
        XLayout: (typeof import('./../components/layout/x-layout.vue'))['default'];
        XLogo: (typeof import('./../components/layout/x-logo.vue'))['default'];
        XRadio: (typeof import('./../components/form/components/x-radio.vue'))['default'];
        XSearchForm: (typeof import('./../components/form/x-search-form.vue'))['default'];
        XSelect: (typeof import('./../components/form/components/x-select.vue'))['default'];
        XUser: (typeof import('./../components/layout/x-user.vue'))['default'];
    }
    export interface ComponentCustomProperties {
        vLoading: (typeof import('element-plus/es'))['ElLoadingDirective'];
    }
}
