/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        Breadcrumb: (typeof import('./../components/x-layout/Breadcrumb.vue'))['default'];
        copy: (typeof import('./../components/x-file-preview/components/excel copy.vue'))['default'];
        ElAside: (typeof import('element-plus/es'))['ElAside'];
        ElAutoResizer: (typeof import('element-plus/es'))['ElAutoResizer'];
        ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb'];
        ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem'];
        ElButton: (typeof import('element-plus/es'))['ElButton'];
        ElCard: (typeof import('element-plus/es'))['ElCard'];
        ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox'];
        ElCheckboxGroup: (typeof import('element-plus/es'))['ElCheckboxGroup'];
        ElCol: (typeof import('element-plus/es'))['ElCol'];
        ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider'];
        ElContainer: (typeof import('element-plus/es'))['ElContainer'];
        ElDescriptions: (typeof import('element-plus/es'))['ElDescriptions'];
        ElDescriptionsItem: (typeof import('element-plus/es'))['ElDescriptionsItem'];
        ElDialog: (typeof import('element-plus/es'))['ElDialog'];
        ElDivider: (typeof import('element-plus/es'))['ElDivider'];
        ElDropdown: (typeof import('element-plus/es'))['ElDropdown'];
        ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem'];
        ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu'];
        ElEmpty: (typeof import('element-plus/es'))['ElEmpty'];
        ElForm: (typeof import('element-plus/es'))['ElForm'];
        ElFormItem: (typeof import('element-plus/es'))['ElFormItem'];
        ElHeader: (typeof import('element-plus/es'))['ElHeader'];
        ElIcon: (typeof import('element-plus/es'))['ElIcon'];
        ElImage: (typeof import('element-plus/es'))['ElImage'];
        ElInput: (typeof import('element-plus/es'))['ElInput'];
        ElMain: (typeof import('element-plus/es'))['ElMain'];
        ElMenu: (typeof import('element-plus/es'))['ElMenu'];
        ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem'];
        ElOption: (typeof import('element-plus/es'))['ElOption'];
        ElPagination: (typeof import('element-plus/es'))['ElPagination'];
        ElPopover: (typeof import('element-plus/es'))['ElPopover'];
        ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup'];
        ElRow: (typeof import('element-plus/es'))['ElRow'];
        ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar'];
        ElSelect: (typeof import('element-plus/es'))['ElSelect'];
        ElTable: (typeof import('element-plus/es'))['ElTable'];
        ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn'];
        ElTableV2: (typeof import('element-plus/es'))['ElTableV2'];
        ElTag: (typeof import('element-plus/es'))['ElTag'];
        ElTooltip: (typeof import('element-plus/es'))['ElTooltip'];
        ElUpload: (typeof import('element-plus/es'))['ElUpload'];
        Excel: (typeof import('./../components/x-file-preview/components/excel.vue'))['default'];
        ExcelLucysheet: (typeof import('./../components/x-file-preview/components/excel-lucysheet.vue'))['default'];
        HistoryTabs: (typeof import('./../components/x-layout/HistoryTabs.vue'))['default'];
        Img: (typeof import('./../components/x-file-preview/components/img.vue'))['default'];
        ParentMenuView: (typeof import('./../components/x-layout/ParentMenuView.vue'))['default'];
        ParentView: (typeof import('./../components/x-layout/ParentView.vue'))['default'];
        Pdf: (typeof import('./../components/x-file-preview/components/pdf.vue'))['default'];
        RouterLink: (typeof import('vue-router'))['RouterLink'];
        RouterView: (typeof import('vue-router'))['RouterView'];
        SubMenu: (typeof import('./../components/x-layout/SubMenu.vue'))['default'];
        TableSetting: (typeof import('./../components/x-table/components/TableSetting.vue'))['default'];
        Word: (typeof import('./../components/x-file-preview/components/word.vue'))['default'];
        XChart: (typeof import('./../components/x-chart/XChart.vue'))['default'];
        XCheckbox: (typeof import('./../components/x-form/components/XCheckbox.vue'))['default'];
        XCrudPage: (typeof import('./../components/x-curd-page/XCurdPage.vue'))['default'];
        XCurdPage: (typeof import('./../components/x-curd-page/XCurdPage.vue'))['default'];
        XDescription: (typeof import('./../components/x-description/XDescription.vue'))['default'];
        XDialogForm: (typeof import('./../components/x-form/XDialogForm.vue'))['default'];
        XDynamicHeaderTable: (typeof import('./../components/x-dynamic-header-table/XDynamicHeaderTable.vue'))['default'];
        XEditTable: (typeof import('./../components/x-edit-table/XEditTable.vue'))['default'];
        XEditTableItem: (typeof import('./../components/x-edit-table/XEditTableItem.vue'))['default'];
        XFilePreview: (typeof import('./../components/x-file-preview/XFilePreview.vue'))['default'];
        XForm: (typeof import('./../components/x-form/XForm.vue'))['default'];
        XFormItem: (typeof import('./../components/x-form/XFormItem.vue'))['default'];
        XLayout: (typeof import('./../components/x-layout/XLayout.vue'))['default'];
        XLogo: (typeof import('./../components/x-layout/XLogo.vue'))['default'];
        XMap: (typeof import('./../components/x-map/XMap.vue'))['default'];
        XRadio: (typeof import('./../components/x-form/components/XRadio.vue'))['default'];
        XRichTextEditor: (typeof import('./../components/x-rich-text-editor/XRichTextEditor.vue'))['default'];
        XSearchForm: (typeof import('./../components/x-form/XSearchForm.vue'))['default'];
        XSelect: (typeof import('./../components/x-form/components/XSelect.vue'))['default'];
        XTable: (typeof import('./../components/x-table/XTable.vue'))['default'];
        XTableV2: (typeof import('./../components/x-table-v2/XTableV2.vue'))['default'];
        XUpload: (typeof import('./../components/x-upload/XUpload.vue'))['default'];
        XUser: (typeof import('./../components/x-layout/XUser.vue'))['default'];
    }
    export interface ComponentCustomProperties {
        vLoading: (typeof import('element-plus/es'))['ElLoadingDirective'];
    }
}
